### PR TITLE
Add Initial Unit Tests

### PR DESCRIPTION
**Pull request by mystoev**
Add the following libraries:
 - **mockito**, **network_image_mock** and **build_runner** for mocking;
 -  **golden_toolkit** for snapshot tests.

Add initial tests for a few files in the ```lib/common``` folder in order to validate the testing strategy and infrastructure.

### CODE REVIEW

**Comment by mystoev** [comment]
@etabakov I added a few simple tests to validate how we want to test things. Particularly, I added the **golden_toolkit** library to make snapshot tests. WDYT about having such tests?

**Comment by etabakov** [comment]
It's a dream come true for me - it will give so much peace of mind when deploying new versions!!
I'd lean on @vakrilov to weigh in on the best technical approach as I don't have too much experience with testing frameworks but definitely would like to invest in that.

**Review by vakrilov — APPROVED** [review]
It is looking awesome 🤩 
I have no much experience in testing in Flutter, but looking at the [docs](https://docs.flutter.dev/testing/overview) this seem like the paved path.

My only suggestion is to delete `test/widget_test.dart` which contains a failing test so that `flutter test` command succeeds and we can incorporate it in the CI actions.

**Comment by etabakov** [comment]
It's exciting that we wouldn't have release the buggy version today if we had these tests :D

**Comment by mystoev** [comment]
Yeah :) Let's add these first, and I can add more PRs with more tests.

**Comment by etabakov** [comment]
Yes. Adding to CI first and then adding more tests sounds like the right sequence to me.

**Pull request merged**
