### PR TITLE
Add Profile Badges

### LINKED ISSUE #97: Add badges for 5kmMAX and SelfieMAX
There are virtual badges that runners receive if they have runs during every single week in the year.

* 5kmMAX is for runners that participated in a official run every week of the year
* SelfieMAX is for runners that participated in with a selfie every week of the year

The badges are attached
Max
MaxSelfie

### PR DESCRIPTION
**Pull request by mystoev**
Fixes #97 

Add badge to the lower right angle of the profile image. See images below:

max
selfie

### CODE REVIEW

**Comment by etabakov** [comment]
UserIDs we can test with: [14](https://5kmrun.bg/5kmrun/user/14), [57](https://5kmrun.bg/5kmrun/user/57), [99](https://5kmrun.bg/5kmrun/user/99), [1469](https://5kmrun.bg/5kmrun/user/1469).
On the website the badge has as number with how many times the badge is claimed, which might be too much for the profile picture. However, the current behaviour in this PR checks for the last year only, right? The badge might be awarded in one of the previous calendar years.

**Comment by mystoev** [comment]
> UserIDs we can test with: [14](https://5kmrun.bg/5kmrun/user/14), [57](https://5kmrun.bg/5kmrun/user/57), [99](https://5kmrun.bg/5kmrun/user/99), [1469](https://5kmrun.bg/5kmrun/user/1469). On the website the badge has as number with how many times the badge is claimed, which might be too much for the profile picture. However, the current behaviour in this PR checks for the last year only, right? The badge might be awarded in one of the previous calendar years.

Yes, it checks only for the current year. I guess that would be enough for now. Later, when we plan to create the badge section, we could elevate that.

**Comment by etabakov** [comment]
My concern is that some users that have the badge from previous year might be disappointed from not seeing it in their profile. Also, it can have strange behaviours like you have it on 31 dec and then on 1 jan you don't have it anymore. 
Could we change the logic to be have the badge "any year" instead of "last year only"?

**Comment by etabakov** [comment]
Looks good to me 👍 It seems we don't have a single runner with MAX Selfie badge won yet or at least I couldn't find one. I don't see any issues with the implementation and MAX officials behaves as expected, so just mentioning to keep an eye on it.

**Pull request merged**
