### PR TITLE
Introduce continuous integration workflow with ios build as a step

### PR DESCRIPTION
**Pull request by etabakov**

### CODE REVIEW

**Comment by etabakov** [comment]
@vakrilov wondering whether it's worth having this run at push and pull_request or that's an overkill? WDYT?

**Comment by vakrilov** [comment]
I'm guessing we'd want to fit in the [free plan for now](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#included-storage-and-minutes). Which is 2000 / 10 (macOS multiplier) = `200 minutes`. 
The [build times](https://github.com/etabakov/fivekmrun-app/actions/workflows/continuous-integration-build.yml) so far are between 5 and 10 mins, so this makes around 20-40 builds a month, which is not much. 

Ultimately I think we can need 2 kins of actions:
- [CI] Run tests (when we have such). Maybe it's better to start with android as we should be able to use linux which is x10 cheaper
- Build packages needed for publishing to the stores. I think it best to trigger when release is created. We will need macOS there to build for AppStore ;)

**Comment by etabakov** [comment]
There are cases, especially when updating tooling when one of the native builds will succeed and the other won't. That's why I was thinking we can build both apps. However, we definitely want to stay in the free plan. Maybe run the iOS more rarely somehow?

**Comment by etabakov** [comment]
Turned out GitHub actions is free for public repos, so merging as is. Thanks GitHub!

**Pull request merged**
